### ISSUE TITLE
[Troubleshooting] Istio AuthorizationPolicy를 사용하여 특정 외부 IP에서만 관리자 API 엔드포인트에 접근할 수 있도록 제한

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#28]
**Issue Description / 이슈 설명**
발생한 문제에 대해 간단히 설명해주세요

api endpoint 중 일부만 회사내부에서만 호출 가능하도록 설정 요청

**Steps to Reproduce / 재현 단계**
문제를 재현하기 위한 단계를 설명해주세요:
1. 접근을 제한하고자 하는  api endpoint 설정
2. Istio CR 설정 ( gw, vs, dr )
3. 추가적인 CR - AuthorizationPolicy

**Expected Behavior / 예상 동작**
정상적으로 작동했을 때 예상되는 동작을 설명해주세요

AuthorizationPolicy까지 등록했을 때 해당 endpoint 는 내부에서만 접근이 가능해야함

**Actual Behavior / 실제 동작**
실제로 발생한 동작이나 오류를 설명해주세요

**Logs / 로그**
관련된 로그나 오류 메시지를 첨부해주세요

```
여기에 로그를 붙여넣으세요
```

**Configuration / 설정**
문제와 관련된 Istio 설정이나 YAML 파일을 첨부해주세요

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: admin-api-external
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks: ["<내부아이피>"]
    to:
    - operation:
        paths: ["/<접근 제한 할endpoint>/*"]
```

**Attempted Solutions / 시도한 해결 방법**
문제를 해결하기 위해 시도해본 방법이 있다면 설명해주세요

**Impact / 영향**
이 문제가 서비스나 사용자에게 미치는 영향이 있다면 설명해주세요

**Additional Context / 추가 정보**
문제 해결에 도움이 될 만한 추가 정보나 스크린샷이 있다면 첨부해주세요
