### ISSUE TITLE
[Troubleshooting] Route53 에서 priavte hosting 영역 등록 시 eks내부에서 client<->server 통신 시 클러스터 내부 통신이 되는 지

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#38]
**Issue Description / 이슈 설명**
발생한 문제에 대해 간단히 설명해주세요

**Steps to Reproduce / 재현 단계**
문제를 재현하기 위한 단계를 설명해주세요:
1.
2.
3.

**Expected Behavior / 예상 동작**
정상적으로 작동했을 때 예상되는 동작을 설명해주세요

**Actual Behavior / 실제 동작**
실제로 발생한 동작이나 오류를 설명해주세요

**Logs / 로그**
관련된 로그나 오류 메시지를 첨부해주세요

```
여기에 로그를 붙여넣으세요
```

**Configuration / 설정**
문제와 관련된 Istio 설정이나 YAML 파일을 첨부해주세요

```yaml
여기에 설정 파일을 붙여넣으세요
```

**Attempted Solutions / 시도한 해결 방법**
문제를 해결하기 위해 시도해본 방법이 있다면 설명해주세요

**Impact / 영향**
이 문제가 서비스나 사용자에게 미치는 영향이 있다면 설명해주세요

**Additional Context / 추가 정보**
문제 해결에 도움이 될 만한 추가 정보나 스크린샷이 있다면 첨부해주세요

1. Route53 Public / Private hosting 영역 중 우선순위는?
2. Private hosting 영역이 먼저 평가된다면 해당 A 레코드에 무슨 값을 넣어야 하는가? -> k8s svc endpoint?
3. 1,2번을 했을 때 client <-> server 통신 시 외부로 나가 NAT GW 거치지 않고 클러스터 내부 통신으로 처리되는가?

**Comment by ByeongHunKim** [comment]
# 1번 : Route53 Public / Private hosting 영역 중 우선순위
- Private Hosted Zone으로 정의한 Private DNS는 Public DNS보다 우선순위가 높다. 따라서 Private Subnet의 서버들이 도메인을 조회할 때 Private Hosted Zone을 먼저 검색한다.
   - https://mystria.github.io/archivers/practical-route53-private-hosted-zone
   - https://popcorn-overflow.tistory.com/33

**Comment by ByeongHunKim** [comment]
# 2번 : Private hosting 영역이 먼저 평가된다면 해당 A 레코드에 무슨 값을 넣어야 하는가? -> k8s svc endpoint?
- private hosting zone
   - A레코드를 생성해서 clusterIP를 넣어도 안됨
   - CNAME 레코드를 생성해서 svc endpoint를 넣어도 안됨
- eks cluster pod 안에서 dig, curl 요청을 날리면 요청이 가는데 도메인에서 API를 호출하면 안됨

---
- 생각해보니 애초에 istio-ingressgateway가 클러스터 엣지에서 트래픽을 받고 있는데 ( public alb 매핑 ) 직접 clusterIP나 svc endpoint를 넣어주었을 때 동작한다고 하면 istio-envoy를 거치지 않고 바로 트래픽을 전달해주는 느낌이라 옳지 않은 것 같음

## istio-system ns에 internal-alb를 연결한 별도의 ingress를 생성해서 istio-ingressgateway에 연결
- 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-alb
  namespace: istio-system
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: <acm인증서 arn>
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 443
```
