### ISSUE TITLE
week13

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#45]
# 실습 진행

- 계획 작성
- 결과 공유

**Comment by ByeongHunKim** [comment]
# 실습 계획
- 기존에 배포 해둔 nest backend project에 istio CR (`VirtualService, DestinationRule` )에서 안 써본 값을 써보기
- 서킷브레이킹, rate limiting

**Comment by opp-13** [comment]
# 실습 계획
- EKS ALB 환경에서의 Header 확인 (x-forwarded-for 위주로)

**Comment by ByeongHunKim** [comment]
# 실습 과정

## DestinationRule

```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: production-destination-rule
  namespace: nestjs-boilerplate
spec:
  host: production-auto-deploy
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 7
      interval: 5m
      baseEjectionTime: 15m
  subsets:
    - labels:
        app.kubernetes.io/name: production
      name: production
```
### [OutlierDetection](https://istio.io/latest/docs/reference/config/networking/destination-rule/#:~:text=No-,OutlierDetection,-A%20Circuit%20breaker)

### consecutive5xxErrors: 7
서비스가 연속해서 7번의 5XX 에러를 반환하면 해당 인스턴스를 불안정하다고 판단


### interval: 5m
- 5분마다 에러를 체크하는 주기
- 5분이 지나면 에러 카운터가 리셋됨


### baseEjectionTime: 15m
- 문제가 있다고 판단된 인스턴스를 15분 동안 로드밸런싱 풀에서 제외
- 15분 후에 다시 트래픽을 받기 시작
