### ISSUE TITLE
week14

### ISSUE THREAD

**Issue by ByeongHunKim** [ByeongHunKim/Cloudclub-istio-skyline#46]
# 마지막 스터디

**Comment by ByeongHunKim** [comment]
#  [week13](https://github.com/ByeongHunKim/Cloudclub-istio-skyline/issues/45#issuecomment-2531033758) 에서 만들어뒀던 dr로 하게되면 5xx 대 에러가 나도 서비스 접근이 가능해서 수정함

```yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: production-destination-rule
  namespace: nestjs-boilerplate
spec:
  host: production-auto-deploy
  trafficPolicy:
    connectionPool:      # 연결 풀 설정 추가
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 1m
      maxEjectionPercent: 100
      minHealthPercent: 0
  subsets:
    - name: production
      labels:
        app.kubernetes.io/name: production
```

## 결과

### 에러 발생
![Image](https://github.com/user-attachments/assets/aa834780-d2af-40f1-9792-8b3209c8ddd8)

### 서비스 접근 불가
<img width="436" alt="image" src="https://github.com/user-attachments/assets/0177f26b-126e-4457-886d-dad5d9428d42" />

## 체크리스트

- 내가 500에러를 냈을 때 다른 사람들은 정상접근이 되는 지 확인

**Comment by ByeongHunKim** [comment]
## 연결 풀 설정 (Connection Pool)

```yaml
connectionPool:
  tcp:
    maxConnections: 100          # TCP 최대 연결 수
  http:
    http1MaxPendingRequests: 1   # 대기 중인 HTTP/1.1 요청 수
    maxRequestsPerConnection: 1   # 연결당 최대 요청 수
```
- maxConnections: 한 시점에 유지할 수 있는 최대 TCP 연결 수
- http1MaxPendingRequests: 대기열에 넣을 수 있는 HTTP/1.1 요청의 최대 수
- maxRequestsPerConnection: 하나의 연결에서 처리할 수 있는 최대 요청 수 (keep-alive 관련)

## 이상 감지 설정 (Outlier Detection)
- [서킷 브레이커](https://itnp.kr/post/istio-circuit-break)처럼 동작하는 이상값 감지 ( outier detection ) 을 수행해 오동작하는 엔드포인트를 로드밸런싱 풀에서 제거 가능

```yaml
outlierDetection:
  consecutive5xxErrors: 1        # 연속된 5xx 에러 횟수
  interval: 1s                   # 검사 주기
  baseEjectionTime: 1m          # 기본 차단 시간
  maxEjectionPercent: 100       # 최대 차단 가능 비율
  minHealthPercent: 0           # 최소 정상 서비스 비율
```
- consecutive5xxErrors: 몇 번의 연속된 5xx 에러가 발생하면 차단할지 설정
- interval: 에러를 검사하는 주기
- baseEjectionTime: 문제가 발생한 엔드포인트를 차단하는 기본 시간
- maxEjectionPercent: 전체 엔드포인트 중 최대로 차단할 수 있는 비율 (100%면 모든 엔드포인트 차단 가능)
- minHealthPercent: 최소한 유지해야 하는 정상 엔드포인트의 비율 (0%면 모든 엔드포인트가 차단될 수 있음)
